# Copyright (c) 2020, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl.

  title: "Creacion LB con 2 VMs - Usando Modelo de Terraform para Resource Manager"
  stackDescription: ${Messages.solutionsHub.solutions.computeInstance.stackDescription()}
  schemaVersion: 1.1.0
  version: "20220617"
  locale: "en"

  variableGroups:
  - title: ${Messages.solutionsHub.generalConfig()}
    visible: false
    variables:
    - compartment_ocid
    - tenancy_ocid
    - region
    
  - title: ${Messages.solutionsHub.requiredConfig()}
    visible: true  
    variables:
    - instance_shape

  - title: ${Messages.solutionsHub.optionalConfig()}
    visible: true  
    variables:
    - ssh_public_key
    - user_data


  variables:
    compartment_ocid:
      type: oci:identity:compartment:id
      # type: string
      required: true
      title: ${Messages.solutionsHub.genericVariables.compartment.title()}
      description: ${Messages.solutionsHub.genericVariables.compartment.description()}

    region:
      type: oci:identity:region:name
      required: true
      title: ${Messages.solutionsHub.genericVariables.region.title()}
      description: ${Messages.solutionsHub.genericVariables.region.description()}

    group_number:
      type: text
      required: true
      default: ""
      title: "Escribir solamente el numero"
      description: "Escribir solamente el numero"

    instance_shape:
      type: enum
      required: true
      title: "Tamano de instancia: Seleccione uno de los 2 instancias flexibles"
      description: "Tamano de instancia: Seleccione uno de los 2 instancias flexibles"
      default: "VM.Standard.E4.Flex"
      enum:
      - "VM.Standard.E4.Flex"
      - "VM.Standard.E5.Flex"
      dependsOn:
        compartmentId: compartment_ocid

    ssh_public_key:
      type: oci:core:ssh:publickey
      additionalProps:
        allowMultiple: true
      required: false
      default: [""]
      pattern: "((^(ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)(,((ssh-rsa AAAAB3NzaC1yc2|ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT|ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD|ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj|ssh-ed25519 AAAAC3NzaC1lZDI1NTE5|ssh-dss AAAAB3NzaC1kc3)[0-9A-Za-z+\/]+[=]{0,3})( [^,]*)?)*$"
      title: "Deje vacio o ingrese la llave publica de las instancias"
      description: "Llave publica de las instancias SSH. El instructor tiene la llave privada"

    user_data:
      type: text
      required: false
      default: ""
      title: "Codigo que ejecuta cuando la VM inicia"
      description: "Codigo que ejecuta cuando la VM inicia. Si esta vacia tiene una aplicacion sencilla"